[package]
name = "sebuilder"
version = "0.1.1"
edition = "2024"
description = "Build Scratch Everywhere! from .sb3 files"
authors = ["TurboToad12"]
repository = "https://github.com/turbotoad12/sebuilder"
license-file = "LICENSE"

[dependencies]
git2 = { version = "0.21.0", features = ["https"] }
seahorse = "2.2.0"
reqwest = { version = "0.13.4", features = ["blocking", "json"]}
serde = { version = "1.0.228", features = ["derive"] }
semver = "1.0.28"
regex = "1.7.3"
zip = "8.6.0"
